# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='board',
            new_name='forum',
        ),
    ]
