# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_auto_20171031_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='categories',
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ManyToManyField(related_name='posts', to='forums.Category', verbose_name='category'),
        ),
    ]
