# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_auto_20171031_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.AddField(
            model_name='topic',
            name='categories',
            field=models.ManyToManyField(related_name='topics', to='forums.Category', verbose_name='categories'),
        ),
    ]
